### ISSUE TITLE
cannot read random object id: open /dev/urandom: permission denied

### ISSUE THREAD

**Issue by coneheadusa** [sylabs/singularity-cri#250] opened 2019-04-12 19:55 UTC
What are the steps to reproduce this issue?
-------------------------------------------
Testing  CRI in interactive mode  in sections 3 and 4:
    1. …in window(bash) A start sycri:  sycri -v=10
    2. …in window B (bash) cd singularity-cri/examples; crictl runp net-prod.json

What happens?
-------------
In window A the following error is thrown: 
 panic: cannot read random object id: open /dev/urandom: permission denied
goroutine 1 [running]:
github.com/sylabs/singularity/vendor/github.com/globalsign/mgo/bson.readRandomUint32(0xa0ed04)
        /home/rsmith/go/src/github.com/sylabs/singularity/vendor/github.com/globalsign/mgo/bson/bson.go:236 +0x100
FATAL:   exit status 1
I0412 12:23:51.660863   25995 pod_runtime.go:130] Forcibly stopping pod a069a59e8ede685ebd558dcd13d44547f8362dd5fb7b1d762462556a4a9107ee
I0412 12:23:51.660916   25995 client.go:66] Executing [singularity -q oci kill -s SIGKILL a069a59e8ede685ebd558dcd13d44547f8362dd5fb7b1d762462556a4a9107ee]
...

What were you expecting to happen?
----------------------------------
See output like:
0e0538d57a52d8673b9ad5124dd017087b3f5292f82cb9406c10f270f8f531fa

And be able to execute the following command:
$ sudo crictl pods
POD ID              CREATED             STATE               NAME                NAMESPACE           ATTEMPT
0e0538d57a52d       26 seconds ago      Ready               networking          default             1

Any logs, error output, comments, etc?
----------------------------
(If it’s long, please paste a link to the full output here.)
...

Environment?
----------------------------------------
**OS distribution and version:** 
CentOS Linux release 7.4.1708 (Core)  3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
**go version:** …
go version go1.11.5 linux/amd64
**go env:** …
GOPATH=/home/rsmith/go
**Singularity-CRI version:** …
current
**Singularity version:**
3.1.1-rc1
**Kubernetes version:** 
kubernetes v1.12.5 

Randy Smith
Sr. HPC Engineer
Translational Genomics Research Institute

**Comment by sashayakovtseva** [comment] 2019-04-15 08:33
Hello @coneheadusa, can you provide the output of the following commands?
- `mount`
- `ls -la /dev | grep rand`

**Comment by coneheadusa** [comment] 2019-04-15 14:31
[urandError.txt](https://github.com/sylabs/singularity-cri/files/3080611/urandError.txt)

**Comment by sashayakovtseva** [comment] 2019-04-15 14:51
hm, maybe something with cgroups?  
please provide also the following output (when CRI is started):
- `cat /proc/cgroups`
- `cat /proc/<cri_pid>/cgroups`

**Comment by sashayakovtseva** [comment] 2019-04-15 14:55
also I would recommend you to stop and disable docker daemon on the host where you install singularity-CRI :)

**Comment by coneheadusa** [comment] 2019-04-16 16:23
Thank you for the reminder re. docker.  

Here is the information you requested:

cat /proc/cgroups
subsys_name	hierarchy	num_cgroups	enabled
cpuset	5	12	1
cpu	9	4	1
cpuacct	9	4	1
memory	2	4	1
devices	3	47	1
freezer	4	12	1
net_cls	6	12	1
blkio	10	4	1
perf_event	7	12	1
hugetlb	8	12	1

 cat /proc/21286/cgroup 
10:blkio:/user.slice
9:cpuacct,cpu:/user.slice
8:hugetlb:/
7:perf_event:/
6:net_cls:/
5:cpuset:/
4:freezer:/
3:devices:/user.slice
2:memory:/user.slice
1:name=systemd:/user.slice/user-1520393138.slice/session-17062.scope

**Comment by sashayakovtseva** [comment] 2019-04-16 19:42
On behalf of what user you run Singularity-CRI? Are you able to run `cat /dev/urandom` from terminal as the same user?

**Comment by sashayakovtseva** [comment] 2019-04-17 15:37
Also try `dmesg` to see if there are any log entries related to this

**Comment by coneheadusa** [comment] 2019-04-18 21:14
As user root I can read /dev/urandom 
cat /dev/urandom > /tmp/ur.out

> od -o /tmp/ur.out | head
0000000 143746 144147 032734 026772 035270 007442 177327 114223
0000020 032300 007053 120560 114614 053044 057751 115152 176575
0000040 073021 120101 040114 030610 054026 167731 064136 067460
0000060 053612 023033 103307 177747 013513 052270 135406 032503
0000100 062527 114612 076127 174202 120256 017224 005542 043464
0000120 172731 012650 007740 077636 013615 033110 041573 030261
0000140 022371 147356 005371 113100 105752 025202 107613 12601

Both the "sycri -v=10"  and the "crictl runp net-pod.json"  commands are being executed as root (UID 0).

I just reran the commands and these are the entries in the dmesg -e output.
Apr18 14:15] IPVS: Creating netns size=2040 id=13
[  +0.027844] overlayfs: missing 'lowerdir'

**Comment by sashayakovtseva** [comment] 2019-04-19 12:34
@coneheadusa really weird behavior since you say root can read from the device. I could not reproduce this issue either. we will try to circumvent `/dev/urandom` reading at all

**Comment by sashayakovtseva** [comment] 2019-04-19 13:08
also do you see this error only when trying to run pod? when simply starting sycri it doesn't appear?

**Comment by tri-adam** [comment] 2019-04-19 13:21
@coneheadusa, if you could `strace` the `sycri` binary, maybe this will give us a hint. Something like:

```sh
strace -o strace.txt -f sycri -v=10
```

(and then the output will be in `strace.txt`)

**Comment by coneheadusa** [comment] 2019-04-19 14:17
The error is thrown only during the execution of the runp command.  Attached is the strace.txt file.

[strace.txt](https://github.com/sylabs/singularity-cri/files/3098352/strace.txt)

**Comment by sashayakovtseva** [comment] 2019-04-19 15:08
can you paste full sycri log output, please?

**Comment by coneheadusa** [comment] 2019-04-19 19:23
New strace and STDERR included in attached.
[straceSTDERR.txt](https://github.com/sylabs/singularity-cri/files/3099095/straceSTDERR.txt)

**Comment by sashayakovtseva** [comment] 2019-04-19 21:33
Interesting, that happens _inside_ the pod process when it starts (oci engine -> start process). we will keep investigating this issue, your latest output is really helpful!

**Comment by sashayakovtseva** [comment] 2019-04-23 07:38
@coneheadusa Just to be on the same page, the example you run has not been changed? Maybe some some security context has been added?

**Comment by sashayakovtseva** [comment] 2019-04-23 08:06
Hello @coneheadusa!  Your issue may happen due to SELinux. Can you provide the following output please to help us understand the problem:
1. `dmesg` output starting from singularity-cri launch and during the error
2. SELinux logs (will be in either of this files: `/var/log/avc.log`, `/var/log/audit/audit.log`, `/var/log/audit.log`) starting from singularity-cri launch and during the error

If it is hard to determine logs needed simply paste whole output in files here, we will find out the piece needed. Thank you for your patience!

**Comment by coneheadusa** [comment] 2019-04-25 15:19
Here is the latest log information:
[sycriLogs2.txt](https://github.com/sylabs/singularity-cri/files/3117605/sycriLogs2.txt)

**Comment by sashayakovtseva** [comment] 2019-04-25 16:12
Can you provide a more detailed output? Take a larger logs slice please, the overlayfs error appears at the very beginning of `starter` running, looks like the interesting part is not included in your file. Same for `audit.log`

**Comment by coneheadusa** [comment] 2019-04-25 17:23
The output from dmesg remains unchanged.   The output in the file below is the result of running 
 autrace  /usr/local/bin/crictl runp net-pod.json  which generates much more detail.  Hope this helps. 

[sycri3.txt](https://github.com/sylabs/singularity-cri/files/3118088/sycri3.txt)

**Comment by sashayakovtseva** [comment] 2019-04-25 20:16
Can you do the same for `sycri`, e.g. `autrace sycri`, please?

**Comment by coneheadusa** [comment] 2019-04-25 20:49
root@sidewinder-login rsmith]# autrace /usr/local/bin/sycri -v=10
Waiting to execute: /usr/local/bin/sycri
I0425 13:46:45.883527   20884 network.go:112] Network configuration found: weave
I0425 13:46:45.883764   20884 main.go:175] Singularity CRI server started on /var/run/singularity.sock
I0425 13:46:45.899460   20884 device.go:97] Loading NVML
E0425 13:46:45.899560   20884 device.go:99] Could not initialize NVML library: could not load NVML library
W0425 13:46:45.899589   20884 main.go:191] GPU support is not enabled: unable to load: check libnvidia-ml.so.1 library and graphic drivers
I0425 13:46:49.187514   20884 pod_validate.go:71] Setting pod cgroup parent to default value "singularity-cri/cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae"
I0425 13:46:49.187555   20884 pod_files.go:88] Creating /var/run/singularity/pods/cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae/namespaces
I0425 13:46:49.187601   20884 pod_files.go:123] Creating log directory /tmp/net-pod
I0425 13:46:49.187713   20884 pod_files.go:106] Creating hostname file /var/run/singularity/pods/cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae/hostname
I0425 13:46:49.199403   20884 pod_files.go:132] Creating /var/run/singularity/pods/cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae/bundle/rootfs
I0425 13:46:49.199477   20884 pod_files.go:141] Creating oci config /var/run/singularity/pods/cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae/bundle/config.json
I0425 13:46:49.200321   20884 pod_runtime.go:49] Creating pod cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae
I0425 13:46:49.200361   20884 client_oci.go:121] Executing [singularity -q oci create --empty-process --sync-socket /var/run/singularity/pods/cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae/sync.sock -b /var/run/singularity/pods/cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae/bundle cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae]
I0425 13:46:49.259289   20884 sync.go:75] Received state 1 at /var/run/singularity/pods/cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae/sync.sock
panic: cannot read random object id: open /dev/urandom: permission denied

goroutine 1 [running]:
github.com/sylabs/singularity/vendor/github.com/globalsign/mgo/bson.readRandomUint32(0xa0ed04)
	/home/rsmith/go/src/github.com/sylabs/singularity/vendor/github.com/globalsign/mgo/bson/bson.go:236 +0x100
FATAL:   exit status 1
I0425 13:46:49.301875   20884 pod_runtime.go:130] Forcibly stopping pod cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae
I0425 13:46:49.301964   20884 client.go:66] Executing [singularity -q oci kill -s SIGKILL cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae]
FATAL:   cannot kill 'cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae', the state of the container must be created or running
E0425 13:46:49.319736   20884 pod.go:100] Could not kill pod after failed run: could not terminate pod: could not execute: exit status 255
I0425 13:46:49.319773   20884 sync.go:63] Context is done
E0425 13:46:49.319835   20884 sync.go:113] Accept failed: accept unix /var/run/singularity/pods/cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae/sync.sock: use of closed network connection
E0425 13:46:49.334765   20884 pod.go:103] Could not remove pod: could not delete instance cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae: FATAL:   no container found with name cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae
I0425 13:46:49.334807   20884 pod_files.go:158] Removing binded namespace /var/run/singularity/pods/cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae/namespaces/uts
I0425 13:46:49.334888   20884 pod_files.go:158] Removing binded namespace /var/run/singularity/pods/cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae/namespaces/network
I0425 13:46:49.334946   20884 pod_files.go:158] Removing binded namespace /var/run/singularity/pods/cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae/namespaces/ipc
I0425 13:46:49.335012   20884 pod_files.go:158] Removing binded namespace 
I0425 13:46:49.335029   20884 pod_files.go:164] Removing pod base directory /var/run/singularity/pods/cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae
I0425 13:46:49.335718   20884 pod_files.go:169] Removing pod log directory /tmp/net-pod
E0425 13:46:49.336685   20884 main.go:54] /runtime.v1alpha2.RuntimeService/RunPodSandbox
	Request: {"config":{"metadata":{"name":"networking","uid":"networking-pod-uid","namespace":"default","attempt":1},"hostname":"networking","log_directory":"/tmp/net-pod","port_mappings":[{"container_port":80}],"linux":{"cgroup_parent":"singularity-cri/cad4ebd8ca6e0e90f6a8b03e3d4f02b8d70d06a5403209e6f249b81377e58fae"}}}
	Response: null
	Error: rpc error: code = Internal desc = could not run pod: could not spawn pod: could not create pod: could not execute create container command: exit status 255

**Comment by cclerget** [comment] 2019-04-26 07:21
@coneheadusa Unfortunately `sycri3.txt` doesn't contain log for the executable we are looking for, could you run a first terminal :

```
autrace /usr/local/bin/sycri -v=10
```

and run in a second terminal :

```
crictl runp net-pod.json
```

then go back to first terminal to interrupt sycri process and run :

```
ausearch -x /usr/local/bin/singularity > /tmp/sing-cli.txt
ausearch -x /usr/local/libexec/singularity/bin/starter > /tmp/sing-runtime.txt
```

And paste `sing-cli.txt` and `sing-runtime.txt` content if any

**Comment by coneheadusa** [comment] 2019-04-29 14:25
The 
"ausearch -x /usr/local/libexec/singularity/bin/starter > /tmp/sing-runtime.txt" command returned "<no matches>" 
The output from "ausearch -x /usr/local/bin/singularity > /tmp/sing-cli.txt" is attached.
[sing-cli.txt](https://github.com/sylabs/singularity-cri/files/3127771/sing-cli.txt)

**Comment by sashayakovtseva** [comment] 2019-05-02 09:21
@coneheadusa Can you try to call oci engine directly instead of via cri and then tell us whether you have the same error? Here's the commands: 
```
$ mkdir /tmp/bundle
$ mkdir /tmp/bundle/rootfs
$ cat  > /tmp/bundle/config.json <<EOF
{
  "ociVersion": "1.0.1-dev",
  "process": {
    "user": {
      "uid": 0,
      "gid": 0
    },
    "args": [
      "true"
    ],
    "cwd": "/"
  },
  "root": {
    "path": "rootfs"
  },
  "hostname": "networking",
  "mounts": [
    {
      "destination": "/proc",
      "type": "proc",
      "source": "proc"
    }
  ],
  "linux": {
    "cgroupsPath": "singularity-cri/44c0b134fa9264d1c41d0e7deefbe84e77e1b960ecb27811f037ddf595772da2",
    "namespaces": [
      {
        "type": "uts"
      },
      {
        "type": "network"
      },
      {
        "type": "pid"
      },
      {
        "type": "mount"
      }
    ]
  }
}
EOF

$ sudo singularity oci create --empty-process -b /tmp/bundle testing
$ sudo singularity oci start testing
```

**Comment by coneheadusa** [comment] 2019-05-02 15:52
No output in shell where create and start  commands were executed and the shell will produce only one NL after several CRs. 
   [root@sidewinder-login rsmith]# singularity oci create --empty-process -b /tmp/bundle testing
   [root@sidewinder-login rsmith]# singularity oci start testing

Output in dmesg:
[May 2 08:21] overlayfs: missing 'lowerdir'
[  +0.091360] IPVS: Creating netns size=2040 id=7

Container appears to be running:
[root@sidewinder-login etc]# singularity oci state testing
{
	"ociVersion": "1.0.1-dev",
	"id": "testing",
	"status": "running",
	"pid": 24688,
	"bundle": "/tmp/bundle",
	"createdAt": 1556810459104353433,
	"startedAt": 1556810467843592762,
	"attachSocket": "/var/run/singularity/instances/oci/root/testing/attach.sock",
	"controlSocket": "/var/run/singularity/instances/oci/root/testing/control.sock"
}

**Comment by coneheadusa** [comment] 2019-05-02 15:53
[root@sidewinder-login etc]# lsof -p 24688
COMMAND   PID USER   FD      TYPE DEVICE SIZE/OFF       NODE NAME
starter 24688 root  cwd       DIR   8,19       39 2167722843 /
starter 24688 root  rtd       DIR   8,19       39 2167722843 /
starter 24688 root  txt       REG   8,19 14701136    4823299 /usr/local/libexec/singularity/bin/starter
starter 24688 root  mem       REG   8,19  2127336 4297183218 /usr/lib64/libc-2.17.so
starter 24688 root  mem       REG   8,19   266680 4298697388 /usr/lib64/libseccomp.so.2.3.1
starter 24688 root  mem       REG   8,19   144792 4297183249 /usr/lib64/libpthread-2.17.so
starter 24688 root  mem       REG   8,19   164112 4299153684 /usr/lib64/ld-2.17.so
starter 24688 root    0u      CHR  136,3      0t0          6 /dev/pts/3
starter 24688 root    1u      CHR  136,3      0t0          6 /dev/pts/3
starter 24688 root    2u      CHR  136,3      0t0          6 /dev/pts/3
starter 24688 root    3r      CHR    1,9      0t0       1033 /dev/urandom
starter 24688 root    4r      CHR    1,9      0t0 6457007975 /dev/urandom
starter 24688 root    5r     FIFO    0,8      0t0    2138148 pipe
starter 24688 root    6w     FIFO    0,8      0t0    2138148 pipe
starter 24688 root    7r     FIFO    0,8      0t0    2138149 pipe
starter 24688 root    8w     FIFO    0,8      0t0    2138149 pipe
starter 24688 root    9r     FIFO    0,8      0t0    2138150 pipe
starter 24688 root   10w     FIFO    0,8      0t0    2138150 pipe
starter 24688 root   11u  a_inode    0,9        0       5971 [eventpoll]

**Comment by sashayakovtseva** [comment] 2019-05-03 07:39
@coneheadusa can I ask you to checkout singularity-CRI master branch? we got rid of a package that reads from `/dev/urandom`, maybe that will help since oci engine works fine when calling directly.

**Comment by coneheadusa** [comment] 2019-05-07 16:44
The results from the latest master branch yield the same /dev/urandom error.   I've attached the STDOUT/STDERR  from the sycri -v=10 command and an strace from the  crictl runp net-pod.json command.  

[singularity-cri4.txt](https://github.com/sylabs/singularity-cri/files/3153681/singularity-cri4.txt)

**Comment by sashayakovtseva** [comment] 2019-05-13 15:46
@coneheadusa The latest strace tracks `crictl` system calls which actually don't reflect `sycri` & `singularity` syscalls made during pod creation. Can you please do the same stdout/err capture along with starting `sycri` as the following: 
```strace -o strace.txt -f sycri -v=10```

**Comment by coneheadusa** [comment] 2019-05-22 20:45
I've included two text files. strace-crictl.txt is the strace and STDOUT/STDERR for this command: 
                           `strace -o strace-crictl.txt crictl runp net-pod.json`
and strace-sycri.txt is the strace and STDOUT/STDERR from this command:
                           `strace -o strace-sycri.txt sycri -v=10`
[strace-crictl.txt](https://github.com/sylabs/singularity-cri/files/3209248/strace-crictl.txt)
[strace-sycri.txt](https://github.com/sylabs/singularity-cri/files/3209249/strace-sycri.txt)

**Comment by sashayakovtseva** [comment] 2019-05-23 15:13
@coneheadusa It looks like the issue appears in singularity runtime, rather than un sycri, so to capture it we need to use strace with `-f` flag that instructs strace to grab info from forks as well (and that is what cri does by calling oci engine). Can you please provide the same output but with `-f` flag used as well? 
I.e.
```
strace -o strace-sycri.txt -f sycri -v=10
strace -o strace-crictl.txt -f crictl runp net-pod.json
```

**Comment by coneheadusa** [comment] 2019-05-29 16:57
Attached are the straces you requested.
[strace-crictl.txt](https://github.com/sylabs/singularity-cri/files/3233580/strace-crictl.txt)
[strace-sycri.txt](https://github.com/sylabs/singularity-cri/files/3233581/strace-sycri.txt)

**Comment by sashayakovtseva** [comment] 2019-05-31 09:49
@coneheadusa
I was unable to reproduce this issue on centOS 7 with `3.10.0-957.5.1.el7.x86_64` kernel, but got the same error on kernel `3.10.0-327.18.2.el7.x86_64`. So it looks like this may be a kernel issue.

Updating singularity to `master` branch where mongo package is already removed solves the issue for kernel `3.10.0-327.18.2.el7.x86_64`.

Another suggestion is to try update kernel version and see if that helps (run `yum list kernel` to see available versions). 

Me and @cclerget will try to find the root of the problem, but right now that looks extremely weird to us. Thank you for your patience!

**Comment by sashayakovtseva** [comment] 2019-05-31 13:32
@coneheadusa pr #277 fixes this issue, thank you for help!

**Closed** 2019-05-31 13:31 UTC
Labels: bug
